import Header from "../components/Header"
import Footer from "../components/Footer"
import Head from "next/head"

const Layout = ({children,title}) => {
  return (
    <>
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
     <Header/>
     <main>{children}</main>
     <Footer/>
    </>
  )
}
Layout.defaultProps={
    title:"My Blog"
}
export default Layout
